### ISSUE TITLE
几个实现的小细节

### ISSUE THREAD

**Issue by Zehaos** [yeahkun/caffe-yolo#1]
Hi, hukun,
I found your code has some difference with the author's, I think it is reasonable, and it indeed work well.
I also implemented the detection layer in python, but my training is not so smooth. 
I would appreciate if you to do some explaination for the differences kindly:
1.
`    // if sqrt_ is true, it should have sqrt with respect to 'w' and 'h'

for (int o = 0; o < 4; ++o) {
        diff[box_index + o * locations] = coord_scale_ * (best_box[o] - true_box[o]);
      }
`

2.
`// truth.x /= l.side... instead

      if (constriant_) {
        true_box[0] = true_box[0] * side_ - Dtype(j % side_);
        true_box[1] = true_box[1] * side_ - Dtype(j / side_);
      }
`

**Comment by Zehaos** [comment]
And the second problem, how to deal with this situation(more than one object in a grid, for the training data)
![123](https://cloud.githubusercontent.com/assets/11896048/18474315/0e73aaaa-79f4-11e6-8c51-06fa78d02aaf.jpg)

**Comment by yeahkun** [comment]
Hi, @Zehaos , thank you for your questions.

For the first question, you can see <https://github.com/yeahkun/caffe-yolo/blob/master/src/caffe/layers/detection_loss_layer.cpp#L163>. Actually, the true w & h have been sqrt, and I let the outputs directly regress to the sqrt values. 

For the second question, I tried to implement the author's original method (truth.x /= l.side, that is, set constraint_ = false in my case), but I found it seems hard to converge (maybe, I'm not sure,).

For the multiple boxes problem, you can see <https://github.com/yeahkun/caffe-yolo/blob/master/src/caffe/layers/box_data_layer.cpp#L175>. I only use one of the boxes in the same grid. I think it's the limit of the method, which is also mentioned in the paper. Maybe you can come up with some ideas to handle this problem.

**Comment by Zehaos** [comment]
It helps, thank you very much~

**Comment by sunshineInmoon** [comment]
Hi, @yeahkun ,thank your answer.
I have some doubt about the first question.
These codes from your Project:
if (sqrt_) { 
          box[2] = pow(box[2], 2);
          box[3] = pow(box[3], 2);
        }
if (sqrt_) { 
        true_box[2] = sqrt(true_box[2]);
        true_box[3] = sqrt(true_box[3]);
      }
area_loss += coord_scale_ * pow(best_box[2] - true_box[2], 2);
area_loss += coord_scale_ * pow(best_box[3] - true_box[3], 2);

I think that should be only one "if" not two in here.
I would appreciate if you to do some explanation.

**Comment by Harick1** [comment]
> Hi, @yeahkun ,thank your answer.
> I have some doubt about the first question.
> These codes from your Project:
> if (sqrt_) {
> box[2] = pow(box[2], 2);
> box[3] = pow(box[3], 2);
> }
> if (sqrt_) {
> true_box[2] = sqrt(true_box[2]);
> true_box[3] = sqrt(true_box[3]);
> }
> area_loss += coord_scale_ * pow(best_box[2] - true_box[2], 2);
> area_loss += coord_scale_ * pow(best_box[3] - true_box[3], 2);
> 
> I think that should be only one "if" not two in here.
> I would appreciate if you to do some explanation.

best_box is not box.
