### ISSUE TITLE
error while runing convert.sh

### ISSUE THREAD

**Issue by riadhayachi** [yeahkun/caffe-yolo#23]
F0512 19:52:53.086220  2486 db_lmdb.cpp:13] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir ./lmdb/trainval_lmdb failed
*** Check failure stack trace: ***
    @     0x7faa55e7c5cd  google::LogMessage::Fail()
    @     0x7faa55e7e433  google::LogMessage::SendToLog()
    @     0x7faa55e7c15b  google::LogMessage::Flush()
    @     0x7faa55e7ee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7faa5624a9a0  caffe::db::LMDB::Open()
    @           0x4043dd  main
    @     0x7faa54ded830  __libc_start_main
    @           0x4055c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
any help for this problem

**Comment by tankienleong** [comment]
@riadhayachi I think you need to delete the existing trainval_lmdb folder before you run the convert.sh

**Comment by riadhayachi** [comment]
ok thanks it works

**Comment by riadhayachi** [comment]
now i get this 
i do not know why i chech the files and they exixst but it send me this error
E0517 16:31:39.408536  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2008_006965.jpg
E0517 16:31:39.408573  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2008_003676.jpg
E0517 16:31:39.408609  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2009_000006.jpg
E0517 16:31:39.408643  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2011_002464.jpg
E0517 16:31:39.408674  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2011_002273.jpg
E0517 16:31:39.408787  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2008_007954.jpg
E0517 16:31:39.408824  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2012/JPEGImages/2008_006002.jpg
E0517 16:31:39.408861  2474 io.cpp:86] Could not open or find file /home/riadh/caffe-yolo/VOCdevkit2007VOCdevkit2007/VOC2007/JPEGImages/006842.jpg

**Comment by tankienleong** [comment]
Can you please check does the 2008_006965.xml exist inside the Annotations folder?

**Comment by riadhayachi** [comment]
yes it exist 
i find the problem thanks
