### ISSUE TITLE
error when run ./convert.sh

### ISSUE THREAD

**Issue by batigooal** [yeahkun/caffe-yolo#6]
@yeahkun, i meet a problem when running ./convert.sh

I1227 15:21:08.608003 22007 convert_box_data.cpp:99] Shuffling data
I1227 15:21:08.908648 22007 convert_box_data.cpp:102] A total of 7970 images.
F1227 15:21:08.908772 22007 db_lmdb.cpp:13] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir ./lmdb/trainval_lmdb failed
*** Check failure stack trace: ***
    @     0x7f01d0f895cd  google::LogMessage::Fail()
    @     0x7f01d0f8b433  google::LogMessage::SendToLog()
    @     0x7f01d0f8915b  google::LogMessage::Flush()
    @     0x7f01d0f8be1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f01d136e7d0  caffe::db::LMDB::Open()
    @           0x4043bd  main
    @     0x7f01cf290830  __libc_start_main
    @           0x4055a9  _start
    @              (nil)  (unknown)
Aborted

Do you know how to solve this problem?

Thank you!

**Comment by choasUp** [comment]
you should mkdir lmdb first by hand.

**Comment by yeahkun** [comment]
@batigooal , What @choasUp said is right.

**Comment by mohanadkaleia** [comment]
I have folder created as lmdb, in the same level as convert.sh script, 
But got same error, 
Did I miss something?

**Comment by mohanadkaleia** [comment]
Actually, I got this error, (slightly different than the one listed in the question) 

```
 ./convert.sh 
I0411 21:43:24.670166  5449 convert_box_data.cpp:99] Shuffling data
I0411 21:43:24.670377  5449 convert_box_data.cpp:102] A total of 0 images.
F0411 21:43:24.670413  5449 db_lmdb.cpp:13] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir ../../data/yolo/trainval.txt failed
*** Check failure stack trace: ***
    @     0x7f6b8c3d05cd  google::LogMessage::Fail()
    @     0x7f6b8c3d2433  google::LogMessage::SendToLog()
    @     0x7f6b8c3d015b  google::LogMessage::Flush()
    @     0x7f6b8c3d2e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6b8c7eff80  caffe::db::LMDB::Open()
    @           0x4043dd  main
    @     0x7f6b8b341830  __libc_start_main
    @           0x4055c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

```
